version: '3'
services:
  minimal-notebook:
    image: jitsejan/minimal-notebook
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/opt/data
    environment:
      - GRANT_SUDO=yes
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "8558:8888"
