version: '3'
services:
  minimal-notebook:
    user: root
    privileged: true
    image: jitsejan/minimal-notebook
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/opt/data
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8558:5006"
